spring:
  datasource:
    driver-class-name:
    hikari:
      # how pool size affects rest requests?
      # how to fix latency of our service without increasing the pool size?
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 300 # what is the effect of this?
      auto-commit: false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect