spring:
  datasource:
    driver-class-name:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      connection-timeout: 30000
      auto-commit: false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect